Separate script logic from nftables (#3)
* Separate script logic from nftables

* Separate script logic from nftables 2 (#2)

* Separate script logic from nftables 2

* Separate script logic from nftables 2

* Separate script logic from nftables 2

* Separate script logic from nftables 2

* Separate script logic from nftables 2

* Separate script logic from nftables 2

* Separate script logic from nftables 2

* Separate script logic from nftables 2

* Separate script logic from nftables 2

diff --git a/miniupnpd/configure b/miniupnpd/configure
--- a/miniupnpd/configure
+++ b/miniupnpd/configure
@@ -91,7 +91,7 @@ case "$argv" in
 		echo " --https-key=/path     Path to the HTTPS private key (default to ${HTTPS_KEYFILE})"
 		echo " --uda-version=x.x     Set advertised UPnP version (default to ${UPNP_VERSION_MAJOR}.${UPNP_VERSION_MINOR})"
 		echo " --disable-pppconn     Disable WANPPPConnection"
-		echo " --firewall=<name>     Force firewall type (nftables, iptables, pf, ipf, ipfw)"
+		echo " --firewall=<name>     Force firewall type (nftables, iptables, pf, ipf, ipfw, script)"
 		echo " --libpfctl            Use libpfctl"
 		echo " --iptablespath=/path  Use a specific version of iptables"
 		echo " --disable-fork        Do not go to background and do not write pid file"
@@ -715,6 +715,17 @@ case $FW in
 			echo "Warning: no libnftnl or libmnl pkg-config found"
 		fi
 		;;
+	script)
+		if ! [ "$OS_FAMILY" = "Linux" ] ; then
+			echo "Error: --firewall=$FW is only available on Linux"
+			exit 1
+		fi
+
+		MAKEFILE=Makefile.linux_script
+		echo "#define USE_NETFILTER 1" >> ${CONFIGFILE}
+		echo "#define USE_EXTERNAL_SCRIPT 1" >> ${CONFIGFILE}
+		echo "/* External script support - no direct firewall manipulation */" >> ${CONFIGFILE}
+		;;
 	*)
 		echo "Unknown Firewall/packet filtering software [$FW]"
 		echo "Please contact the author at http://miniupnp.free.fr/ or https://miniupnp.tuxfamily.org/."
@@ -722,7 +733,7 @@ case $FW in
 		;;
 esac
 
-if [ "$MAKEFILE" = "Makefile.linux" ] || [ "$MAKEFILE" = "Makefile.linux_nft" ] || [ "$MAKEFILE" = "Makefile.macosx" ] ; then
+if [ "$MAKEFILE" = "Makefile.linux" ] || [ "$MAKEFILE" = "Makefile.linux_nft" ] || [ "$MAKEFILE" = "Makefile.linux_script" ] || [ "$MAKEFILE" = "Makefile.macosx" ] ; then
 	DEFAULT_CONFIG=/etc/miniupnpd/miniupnpd.conf
 else
 	DEFAULT_CONFIG=/etc/miniupnpd.conf
